### Basic authorization.
GET https://ijhttp-examples.jetbrains.com/basic-auth/user/passwd
Authorization: Basic user passwd

### Basic authorization with variables.
GET https://ijhttp-examples.jetbrains.com/basic-auth/user/passwd
Authorization: Basic {{username}} {{password}}

### Digest authorization.
GET https://ijhttp-examples.jetbrains.com/digest-auth/realm/user/passwd
Authorization: Digest user passwd

### Digest authorization with variables.
GET https://ijhttp-examples.jetbrains.com/digest-auth/realm/user/passwd
Authorization: Digest {{username}} {{password}}

### Authorization by token, part 1. Retrieve and save token.
POST https://ijhttp-examples.jetbrains.com/post
Content-Type: application/json

{
  "token": "my-secret-token"
}

> {% client.global.set("auth_token", response.body.json.token); %}

### Authorization by token, part 2. Use token to authorize.
GET https://ijhttp-examples.jetbrains.com/headers
Authorization: Bearer {{auth_token}}

# Note
// Due to the ijhttp-examples.jetbrains.com POST implementation,
// we use `response.body.json.token` to retrieve the token.
// Depending on the actual web service you are interacting with,
// the response structure may differ, and you may need to use a different construction,
// for example, `response.body.token`